spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/furniture
    username: postgres
    password: come on
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
jwt:
  access:
    key: cksdIOJHGytgyuhd4651846DE7E0plmnlo22455hkfjsieioef45785654czxdkcjasincosaffd
    expiration-time: 7200000000
  refresh:
    key: kjecnjewk4896213-={}]'dqKJBBUI77y)0@#!£485142
    expiration-time: 604800000

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html