package com.example.allforyourhome.utils;

public interface MessageConstants {

    String PHONE_ALREADY_REGISTERED = "PHONE ALREADY REGISTERED";
    String USER_NOT_FOUND_OR_DISABLED = "USER NOT FOUND OR DISABLED";
    String LOGIN_OR_PASSWORD_ERROR = "LOGIN OR PASSWORD ERROR";
    String PASSWORD_SUCCESSFULLY_CHANGED = "PASSWORD SUCCESSFULLY CHANGED";
    String PASSWORDS_AND_PRE_PASSWORD_NOT_EQUAL = "PASSWORDS AND PRE PASSWORD NOT EQUAL";
    String USER_NOT_FOUND = "USER NOT FOUND";
    String PASSWORD_CAN_NOT_BE_EMPTY = "PASSWORD CAN NOT BE EMPTY";
    String PHONE_NUMBER_CAN_NOT_BE_EMPTY = "PHONE NUMBER CAN NOT BE EMPTY";
    String PHONE_NUMBER_SHOULD_MATCH_REGEX = "PHONE NUMBER SHOULD MATCH REGEX";
    String PASSWORD_SHOULD_MATCH_REGEX = "PASSWORD SHOULD MATCH REGEX";
    String DO_NOT_HAVE_PERMISSION_TO_USE_THIS_WAY = "DO NOT HAVE PERMISSION TO USE THIS WAY";
    String PAGE_NOT_FOUND = "PAGE NOT FOUND";
    String METHOD_ERROR = "METHOD ERROR";
    String UNACCEPTABLE = "UNACCEPTABLE";
    String FIRST_NAME_CAN_NOT_BE_EMPTY = "FIRST NAME CAN NOT BE EMPTY";
    String LAST_NAME_CAN_NOT_BE_EMPTY = "LAST NAME CAN NOT BE EMPTY";
    String PRE_PASSWORD_CAN_NOT_BE_EMPTY = "PRE PASSWORD CAN NOT BE EMPTY";
    String ACCOUNT_CREATED = "ACCOUNT CREATED";
    String VERIFIED = "VERIFIED";
    String VERIFICATION_CODE_INCORRECT_OR_USED = "VERIFICATION CODE INCORRECT OR USED";
    String PAGE_OR_SIZE_ERROR = "PAGE AND SIZE MUST BE GREATER THAN 0 OR 1";
    String USER_NOT_FOUND_WITH_ID = "USER NOT FOUND WITH ID: ";
    String USER_ALREADY_VERIFIED = "USER ALREADY VERIFIED";
    String PASSWORD_SHOULD_CONTAIN_LOWER_CASE = "Password should contain at least one lower case";
    String PASSWORD_SHOULD_CONTAIN_UPPER_CASE = "Password should contain at least one upper case";
    String PASSWORD_SHOULD_CONTAIN_SPECIAL_SYMBOL = "Password should contain at least one special character(@!?£$%^&-+*=/\\_)";
    String PASSWORD_SHOULD_CONTAIN_MIN_8_CHARACTERS = "Password should contain at least 8 characters";
    String PASSWORD_SHOULD_CONTAIN_MAX_30_CHARACTERS = "Password should not contain more than 30 characters";
    String PASSWORD_SHOULD_CONTAIN_NUMBERS = "Password should contain numbers";
    String VERIFICATION_CODE_SENT_TO_PHONE_NUMBER = "VERIFICATION CODE SENT TO PHONE NUMBER";
    String SMS_SENT_FOR_FORGOT_PASSWORD = "SMS SENT FOR FORGOT PASSWORD";
    String VERIFICATION_CODE_ALREADY_USED_OR_INCORRECT = "VERIFICATION CODE ALREADY USED OR INCORRECT";
    String MIN_VALUE_IS_100000 = "MIN VALUE IS 100000";
    String MAX_VALUE_IS_999999 = "MAX VALUE IS 999999";
    String VERIFICATION_CODE_CAN_NOT_TO_NULL = "VERIFICATION CODE CAN NOT TO NULL";
    String TOKEN_GENERATED = "TOKEN GENERATED";
    String INCORRECT_VERIFICATION_CODE = "INCORRECT VERIFICATION CODE";
    String UNABLE_TO_GET_TOKEN = "UNABLE TO GET TOKEN";
    String SERVICE_USED_UNAUTHORIZED_TOKEN = "SERVICE USED UNAUTHORIZED TOKEN";
    String SMS_SERVICE_UNAVAILABLE = "SMS SERVICE UNAVAILABLE";
}
